export const properties = [
  {
    id: 1,
    title: "Modern Loft in Downtown",
    location: "San Francisco, CA",
    price: 189,
    rating: 4.9,
    reviews: 127,
    guests: 4,
    bedrooms: 2,
    image: "/modern-loft-apartment-interior-downtown.jpg",
    host: "Sarah",
  },
  {
    id: 2,
    title: "Beachfront Villa with Pool",
    location: "Malibu, CA",
    price: 450,
    rating: 5.0,
    reviews: 89,
    guests: 8,
    bedrooms: 4,
    image: "/luxury-beachfront-villa-pool-ocean-view.jpg",
    host: "Michael",
  },
  {
    id: 3,
    title: "Cozy Mountain Cabin",
    location: "Aspen, CO",
    price: 225,
    rating: 4.8,
    reviews: 156,
    guests: 6,
    bedrooms: 3,
    image: "/cozy-mountain-cabin-snow-fireplace.jpg",
    host: "Emma",
  },
  {
    id: 4,
    title: "Penthouse with City Views",
    location: "New York, NY",
    price: 380,
    rating: 4.9,
    reviews: 203,
    guests: 5,
    bedrooms: 3,
    image: "/luxury-penthouse-city-skyline-view.jpg",
    host: "David",
  },
  {
    id: 5,
    title: "Tropical Bungalow",
    location: "Maui, HI",
    price: 295,
    rating: 4.7,
    reviews: 94,
    guests: 4,
    bedrooms: 2,
    image: "/tropical-beach-bungalow-palm-trees.jpg",
    host: "Olivia",
  },
  {
    id: 6,
    title: "Historic Brownstone",
    location: "Boston, MA",
    price: 175,
    rating: 4.8,
    reviews: 142,
    guests: 6,
    bedrooms: 3,
    image: "/historic-brownstone-interior-elegant.jpg",
    host: "James",
  },
  {
    id: 7,
    title: "Desert Oasis Retreat",
    location: "Scottsdale, AZ",
    price: 210,
    rating: 4.9,
    reviews: 78,
    guests: 4,
    bedrooms: 2,
    image: "/desert-modern-house-pool-cactus.jpg",
    host: "Sophia",
  },
  {
    id: 8,
    title: "Lakeside Cottage",
    location: "Lake Tahoe, CA",
    price: 165,
    rating: 4.6,
    reviews: 118,
    guests: 5,
    bedrooms: 2,
    image: "/lakeside-cottage-dock-mountains.jpg",
    host: "William",
  },
]
