import type { Property } from "./types"

export const properties: Property[] = [
  {
    id: 1,
    title: "Modern Loft in Downtown",
    location: "San Francisco, CA",
    price: 189,
    rating: 4.9,
    reviews: 127,
    guests: 4,
    bedrooms: 2,
    bathrooms: 1,
    images: ["/modern-loft-apartment-interior-downtown.jpg"],
    host: "Sarah",
    description: "Stylish modern loft in the heart of downtown with amazing city views.",
  },
  {
    id: 2,
    title: "Beachfront Villa with Pool",
    location: "Malibu, CA",
    price: 450,
    rating: 5.0,
    reviews: 89,
    guests: 8,
    bedrooms: 4,
    bathrooms: 3,
    images: ["/luxury-beachfront-villa-pool-ocean-view.jpg"],
    host: "Michael",
    description: "Luxurious beachfront villa with private pool and stunning ocean views.",
  },
  {
    id: 3,
    title: "Cozy Mountain Cabin",
    location: "Aspen, CO",
    price: 225,
    rating: 4.8,
    reviews: 156,
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    images: ["/cozy-mountain-cabin-snow-fireplace.jpg"],
    host: "Emma",
    description: "Charming mountain cabin perfect for a winter getaway with fireplace.",
  },
  {
    id: 4,
    title: "Penthouse with City Views",
    location: "New York, NY",
    price: 380,
    rating: 4.9,
    reviews: 203,
    guests: 5,
    bedrooms: 3,
    bathrooms: 2,
    images: ["/luxury-penthouse-city-skyline-view.jpg"],
    host: "David",
    description: "Stunning penthouse with panoramic city skyline views.",
  },
  {
    id: 5,
    title: "Tropical Bungalow",
    location: "Maui, HI",
    price: 295,
    rating: 4.7,
    reviews: 94,
    guests: 4,
    bedrooms: 2,
    bathrooms: 2,
    images: ["/tropical-beach-bungalow-palm-trees.jpg"],
    host: "Olivia",
    description: "Beautiful tropical bungalow steps from the beach with palm trees.",
  },
  {
    id: 6,
    title: "Historic Brownstone",
    location: "Boston, MA",
    price: 175,
    rating: 4.8,
    reviews: 142,
    guests: 6,
    bedrooms: 3,
    bathrooms: 2,
    images: ["/historic-brownstone-interior-elegant.jpg"],
    host: "James",
    description: "Elegant historic brownstone with classic architecture.",
  },
  {
    id: 7,
    title: "Desert Oasis Retreat",
    location: "Scottsdale, AZ",
    price: 210,
    rating: 4.9,
    reviews: 78,
    guests: 4,
    bedrooms: 2,
    bathrooms: 2,
    images: ["/desert-modern-house-pool-cactus.jpg"],
    host: "Sophia",
    description: "Modern desert retreat with pool and beautiful cactus garden.",
  },
  {
    id: 8,
    title: "Lakeside Cottage",
    location: "Lake Tahoe, CA",
    price: 165,
    rating: 4.6,
    reviews: 118,
    guests: 5,
    bedrooms: 2,
    bathrooms: 1,
    images: ["/lakeside-cottage-dock-mountains.jpg"],
    host: "William",
    description: "Peaceful lakeside cottage with dock access and mountain views.",
  },
]
